<?php
return array(
	'id'=>'advert_item_form',
	'elements'=>array(
		'advert_item'=>array(
			'type'=>'form',
			'title'=>'广告信息',			
			'elements'=>array(
	    		'ad_id'=>array(
					'type'=>'hidden',
				),				
				'title'=>array(
					'type'=>'text',
	    			'class'=>'input-text',
					'hint'=>'广告名称，alt',
					'size'=>'40'
				),
				'thumb'=>array(
					'type'=>'application.extensions.wl_fileContent.WLImageUpload',
					'htmlOptions'=>array('class'=>'input-text','size'=>'40'),
				),
				'file_url'=>array(
					'type'=>'application.extensions.wl_fileContent.WLImageUpload',
					'htmlOptions'=>array('class'=>'input-text','size'=>'40'),
				),
				'link_url'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'40'
				),
				'target'=>array(
					'type'=>'radiolist',
					'items'=>array('_self'=>'本窗口打开','_blank'=>'新建窗口打开'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
				),
				'listorder'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'1',
				),
			),
		),
	),
	'buttons'=>array(
		'advert_item_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>true,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnSubmit'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);