<?php
return array(
	'id'=>'column_model_form',
	'elements'=>array(
		'base'=>array(
			'type'=>'form',
			'title'=>'基本选项',			
			'elements'=>array(
	    		'modelid'=>array(
					'type'=>'dropdownlist',
					'items'=>CHtml::listData(ModelObject::model()->wl_getModels(), 'id', 'name'),
	    			'label'=>'请选择模型',
					'prompt'=>'请选择模型',
	    			'hint'=>'模型为必选项，请选择'
				),
				'parentid'=>array(
					'type'=>'dropdownlist',
					'items'=>Column::model()->wl_getColumnOption(),
					'prompt'=>'作为一级菜单',
					'encode'=>false,
				),
				'colname'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'栏目名称为必填项，请填写'
				),
				'keyparam'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'20',
					'hint'=>'此参数为伪静态优化地址',
				),
				'image'=>array(
					'type'=>'application.extensions.wl_fileContent.WLImageUpload',
					'htmlOptions'=>array('class'=>'input-text','size'=>'50'),
				),
				'description'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'height: 60px;',
					'cols'=>'50',
				),
				'dataway'=>array(
					'type'=>'radiolist',
					'items'=>array('1'=>'调用子栏目数据','2'=>'本栏目独立数据','3'=>'调用第一个子栏目数据'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
					'hint'=>'栏目数据调用方式，支持多种栏目数据调用'
				),
				'display'=>array(
					'type'=>'checkbox',
					'class'=>'input-checkbox',
				),
				'target'=>array(
					'type'=>'radiolist',
					'items'=>array('_self'=>'本窗口打开','_blank'=>'新建窗口打开'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
				),
			),
		),
		'seo'=>array(
			'type'=>'form',
			'title'=>'SEO 设置',
			'elements'=>array(
				'metaTitle'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'60',
				),
				'metaKeyword'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'width: 90%;height: 40px;',
				),
				'metaDescription'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'width: 90%;height: 40px;',
				),
			),
		),
	),
	'buttons'=>array(
		'column_model_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>false,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);