<?php
return array(
	'id'=>'column_custom_form',
	'elements'=>array(
		'base'=>array(
			'type'=>'form',
			'title'=>'基本选项',			
			'elements'=>array(
				'parentid'=>array(
					'type'=>'dropdownlist',
					'items'=>Column::model()->wl_getColumnOption(),
					'prompt'=>'作为一级菜单',
					'encode'=>false,
				),
				'colname'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'栏目名称为必填项，请填写'
				),
				'image'=>array(
					'type'=>'application.extensions.wl_fileContent.WLImageUpload',
					'htmlOptions'=>array('class'=>'input-text','size'=>'50'),
				),
				'description'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'height: 60px;',
					'cols'=>'50',
				),
				'display'=>array(
					'type'=>'checkbox',
					'class'=>'input-checkbox',
				),
				'target'=>array(
					'type'=>'radiolist',
					'items'=>array('_self'=>'本窗口打开','_blank'=>'新建窗口打开'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
				),
			),
		),
		'param'=>array(
			'type'=>'form',
			'title'=>'访问地址参数',
			'elements'=>array(
				'm'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'20',
				),
				'c'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'20',
					'hint'=>'控制器为必填项，请填写'
				),
				'a'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'20',
					'hint'=>'控制器方法为必填项，请填写'
				),
				'data'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'为地址参数,格式：s=222&a=33',
				),
			),
		),
		'seo'=>array(
			'type'=>'form',
			'title'=>'SEO 设置',
			'elements'=>array(
				'metaTitle'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'60',
				),
				'metaKeyword'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'width: 90%;height: 40px;',
				),
				'metaDescription'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'width: 90%;height: 40px;',
				),
			),
		),
	),
	'buttons'=>array(
		'column_custom_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>false,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);