<?php
return array(
	'id'=>'menu_form',
	'elements'=>array(
		'menu'=>array(
			'type'=>'form',
			'title'=>'菜单信息',			
			'elements'=>array(
				'parent_id'=>array(
					'type'=>'dropdownlist',
					'items'=>Menu::model()->wl_getMenuOption(),
					'prompt'=>'作为一级菜单',
					'encode'=>false,
				),
	    		'name'=>array(
					'type'=>'text',
	    			'class'=>'input-text',
				),
				'm'=>array(
					'type'=>'text',
					'class'=>'input-text'
				),
				'c'=>array(
					'type'=>'text',
					'class'=>'input-text'
				),
				'a'=>array(
					'type'=>'text',
					'class'=>'input-text',
				),
				'display'=>array(
					'type'=>'radiolist',
					'items'=>array('0'=>'不显示','1'=>'显示','2'=>'弹出显示','3'=>'弹出全屏显示','4'=>'中间iframe显示','5'=>'脚本控制','6'=>'中间iframe菜单','7'=>'主体iframe显示'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
				),
				'data'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'为地址参数或脚本监控key。格式：s=222&a=33或click_search',
				),
				'listorder'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'1',
				),				
				'size'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'如若显示方式为弹出显示，请填写显示尺寸。格式：500*500'
				),
			),
		),
	),
	'buttons'=>array(
		'menu_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>true,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);
