<?php
return array(
	'id'=>'mparam_form',
	'elements'=>array(
		'mparam'=>array(
			'type'=>'form',
			'title'=>'模型可配参数',			
			'elements'=>array(
	    		'name'=>array(
					'type'=>'text',
	    			'class'=>'input-text',
	    			'hint'=>'请输入参数名称',
	    			'size'=>'40',
				),				
				'key'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'请输入参数引用字符串',
					
				),
				'type'=>array(
					'type'=>'dropdownlist',
					'items'=>array('text'=>'文本域','dropdownlist'=>'下拉菜单'),
					'prompt'=>'选择参数类型',
					'hint'=>'需选择参数类型',
				),
				'value_items'=>array(
					'type'=>'textarea',
					'class'=>'input-text',
					'hint'=>'参数类型为下来参数时，请输入参数项',
					'size'=>'40',
				),
				'value_items'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'hint'=>'参数类型为下来参数时，请输入参数项',
					'cols'=>30,
					'rows'=>6
				),
				'default_value'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'请输入默认值',
				),
				'model_field'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'对应模型字段名称',
				),
				'position'=>array(
					'type'=>'radiolist',
					'items'=>array('0'=>'后台','1'=>'前台'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
					'hint'=>'对应前台后台可绑定参数',
				),
				'listorder'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'1',
				),
				'model_id'=>array(
					'type'=>'hidden',
				),
			),
		),
	),
	'buttons'=>array(
		'mparam_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>true,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);
