<?php
return array(
	'id'=>'role_form',
	'elements'=>array(
		'role'=>array(
			'type'=>'form',
			'title'=>'角色信息',			
			'elements'=>array(
	    		'name'=>array(
					'type'=>'text',
	    			'class'=>'input-text',
	    			'hint'=>'角色名称为英文，且唯一',
	    			'size'=>'20'
				),				
				'description'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'描述为角色显示标题',
					'size'=>'20',
				),
				'bizrule'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'业务规则',
					'size'=>'40',
				),
				'data'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'40',
					'hint'=>'输入数组格式'
				),
			),
		),
	),
	'buttons'=>array(
		'role_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
			'id'=>'dosubmit',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>true,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);
