<?php
return array(
	'id'=>'setting_form',
	'elements'=>array(
		'base'=>array(
			'type'=>'form',
			'title'=>'基础设置',			
			'elements'=>array(
	    		'title'=>array(
					'type'=>'text',
	    			'class'=>'input-text',
	    			'size'=>'30',
				),
				'subTitle'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'50',
				),
				'domain'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'格式：http://www.windlife.net,请正确填写',
				),
				'metaKeyword'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'height: 36px;',
					'cols'=>'50',
					'hint'=>'关键词之间请用英文逗号隔开',
				),
				'metaDescription'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'style'=>'height: 36px;',
					'cols'=>'50',
				),
				'email'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'请正确填写邮箱'
				),
				'telephone'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'格式：0532-12345678，请正确填写'
				),
				'phone'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'请正确填写手机号码'
				),
				'fax'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'格式：0532-12345678，请正确填写'
				),
				'zip'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'请正确填写邮编'
				),
				'address'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'50',
				),
				'certs'=>array(
					'type'=>'text',
					'class'=>'input-text',
				),
				'qq1'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'请正确填写QQ号码'
				),
				'qq2'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'请正确填写QQ号码'
				),				
			),
		),
		'upload'=>array(
			'type'=>'form',
			'title'=>'上传设置',
			'elements'=>array(
				'size'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'10',
					'hint'=>'单位为KB'
				),
				'fileType'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'70'
				),
				'isWater'=>array(
					'type'=>'checkbox',
					'class'=>'input-checkbox'
				),
				'waterWith'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'10',
					'hint'=>'单位为PX'
				),
				'waterHeight'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'10',
					'hint'=>'单位为PX'
				),
				'waterName'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'水印存放路径:images/water'
				),
				'waterTouming'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'10',
					'hint'=>'请设置为0-100之间的数字，0代表完全透明，100代表不透明'
				),
				'waterQuality'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'10',
					'hint'=>'水印质量请设置为0-100之间的数字,决定 jpg 格式图片的质量'
				),
				'thumbQuality'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'10',
					'hint'=>'图片缩略图质量请设置为0-100之间的数字,决定 jpg 格式图片的质量'
				),
				'waterPosition'=>array(
					'type'=>'radiolist',
					'items'=>array('1'=>'顶部居左','2'=>'中部居中','3'=>'底部居右'),
					'separator'=>'&nbsp;&nbsp;&nbsp;&nbsp;',
					'class'=>'input-radio',
				),
			),
		),
		'email'=>array(
			'type'=>'form',
			'title'=>'邮箱配置',
			'elements'=>array(
			    'server'=>array(
				    'type'=>'text',
				    'class'=>'input-text',
			       	'size'=>'30'		       
			    ),
			    'port'=>array(
				    'type'=>'text',
					'class'=>'input-text',
			    	'size'=>'10',
			    	'hint'=>'端口为正整数'
				),
				'address'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'发送人地址为邮箱地址'
				),
				'username'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'验证用户名为邮箱地址'
				),
				'password'=>array(
					'type'=>'password',
					'class'=>'input-text',
				),
				'test'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'30',
					'hint'=>'<a rel="mail_test">测试发送</a>'
				),
		    ),
		),
		'count'=>array(
			'type'=>'form',
			'title'=>'统计代码',
			'elements'=>array(
				'code'=>array(
					'type'=>'textarea',
					'class'=>'input-textarea',
					'rows'=>'6',
					'cols'=>'70',
				),
			),
		),
	),
	'buttons'=>array(
		'setting_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>false,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);