<?php
return array(
	'id'=>'urlrule_form',
	'elements'=>array(
		'urlrule'=>array(
			'type'=>'form',
			'title'=>'URL规则信息',			
			'elements'=>array(
			    'module'=>array(
					'type'=>'dropdownlist',
					'items'=>array('无模块'=>'无模块'),
			    	'prompt'=>'选择所属模块',
			    	'hint'=>'需选择所属模块',
				),
	    		'name'=>array(
					'type'=>'text',
	    			'class'=>'input-text',
	    			'hint'=>'请输入URL规则名称',
				),				
				'rule'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'请输入URL规则',
					'size'=>'40',
				),
				'rule_url'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'hint'=>'请输入URL规则对应地址',
					'size'=>'40',
				),
				'page_rule'=>array(
					'type'=>'text',
					'class'=>'input-text',
						'size'=>'50',
				),
				'page_rule_url'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'50',
				),
				'listorder'=>array(
					'type'=>'text',
					'class'=>'input-text',
					'size'=>'1',
				),
			),
		),
	),
	'buttons'=>array(
		'urlrule_form_button'=>array(
			'type'=>'submit',
			'label'=>'提交',
			'class'=>'button',
		),
	),
	'activeForm'=>array(
		'enableAjaxValidation'=>true,
		'enableClientValidation'=>true,
		'clientOptions' => array(
			'validateOnChange'=>true,
			'afterValidateAttribute'=>'js:afterValidate',
		),
	),
);
